### PR TITLE
Fix unbuffered signal channel passed to signal.Notify

### LINKED ISSUE #6: server: unbuffered signal channel could cause signal not to be delivered
Coming here from auditing https://github.com/nat/keyrace/blob/dab1b873b9d84e75220c31d5be6bb08a41c98fbd/server.go#L281-L283

which is a bug as documented in os/signal https://golang.org/pkg/os/signal/#Notify as per:
Screen Shot 2020-11-30 at 9 15 04 PM

For Go1.17, my team is going to release a static analyzer that'll be included  when you run `go test` as per https://github.com/golang/go/issues/9399, but for now, please make that channel buffered.

Our internal static analyzer reports this:
```shell
$ sigchanyzer ./server.go 
github.com/nat/keyrace/server.go:282:2: misuse of unbuffered os.Signal channel as argument to signal.Notify
```
/cc @cuonglm

### PR DESCRIPTION
**Pull request by cuonglm**
Caught by a static analysis tool from Orijtech, Inc. called "sigchanyzer"

While at it, also simplify signals handler code.

Fixes #6

### CODE REVIEW

File: server.go [hunk 1]
```diff
@@ -278,16 +278,14 @@ func main() {
...
+	signals := make(chan os.Signal, 1)
+	signal.Notify(signals, os.Interrupt, syscall.SIGTERM)
 	go func() {
-		for sig := range signals {
-			// Save the file.
-			saveStateToFile(tmpfile)
-			fmt.Printf("Received %s, exiting.\n", sig.String())
-			os.Exit(0)
-		}
+		sig := <-signals
```
Comment (jessfraz) [inline server.go:284]: why would this be necessary if the process is going to exit anyway?

Comment (cuonglm) [reply server.go:284]: What do you mean "this", this line `sig := <-signals`, or the buffered channel?

In any case, if the signal was lost (due to using of unbuffered channel), then these block will never happen, and program will continue running.
